spring:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/fresh?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: rush99123
      
   http:
      encoding:
         force: true
         charset: UTF-8
         enabled: true
      
   session:
      store-type: redis
      
   redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 5000
      jedis: 
         pool: 
            max-active: 8
            
   # 邮件发送配置   
   mail:
      host: smtp.qq.com
      username: 1045556957@qq.com
      password: nfqmrtggyhoybcje
      port: 465
      protocol: smtp
      properties:
         mail:
            smtp: 
               auth: true
               ssl:
                  enable: true
                  
# myvatis配置
mybatis:
   mapper-locations: classpath:mapper/*Mapper.xml
   type-aliases-package: com.yc.fresh.goods.entity # 需要扫描的启用别名的类所在的包
   
eureka:
   client:
      service-url:
         defaultZone: http://root:root@127.0.0.1:6868/eureka
      
      